### ISSUE TITLE
to and from JSON string

### ISSUE THREAD

**Issue by evermeer** [matthewcheok/JSONCodable#1]
The .JSONEncode() method currently encodes to a dictionary. It would be nice if you added a couple of helper functions that use NSJSONSerialization to convert the dictionary to a JSON string (and the other way around). 

If you do so, I think that method should be called JSONEncode() and the original method should be called something like .toDictionary()

**Comment by matthewcheok** [comment]
While it's a good idea, I don't think it should be the default behavior as some networking frameworks actually handle the NSJSONSerialization part for you (see AFNetworking and Alamofire.) Perhaps a `func JSONString()` method might make better sense.

**Comment by matthewcheok** [comment]
Added string methods

**Comment by evermeer** [comment]
Cool! Thanks!
