### ISSUE TITLE
Add a new transform for enums?

### ISSUE THREAD

**Issue by 7studios** [matthewcheok/JSONCodable#11]
Hi Matthew,

It would be great to have support for enums as well in JSONTransformer.

Great work!

**Comment by matthewcheok** [comment]
I don't believe we can add a transformer for all enums unless maybe they conform to a certain protocol. Do you have a sample for what you might want that to look like?

**Comment by 7studios** [comment]
Maybe string enums, below is what I implemented.

public enum TemperatureFormat: String {
        case Automatic, Celsius, Fahrenheit
}

public init?(JSONDictionary: [String : AnyObject]) {  
        do {
            celsius = try JSONDictionary.decode("celsius")
            fahrenheit = try JSONDictionary.decode("fahrenheit")
            format = try TemperatureFormat(rawValue: JSONDictionary.decode("format"))!  
        }
        catch {
            print(error)
            return nil
        }
}

**Comment by matthewcheok** [comment]
You can now use enums (without a transformer!)
