### ISSUE TITLE
init?(JSONDictionary: JSONObject) should throw

### ISSUE THREAD

**Issue by srdanrasic** [matthewcheok/JSONCodable#16]
Hi @matthewcheok,

Kudos for the library! I have just one question. Why is the initializer `init?(JSONDictionary: JSONObject)` a failable initializer rather than a throwing one? Sometime one might want the handle the error from the outside...

Thanks!

**Comment by matthewcheok** [comment]
Partly due to historical reasons, because throwing initialisers don't seem to be as prevalent as failable ones. Would there be any case you want to handle the specific error instead of checking for `nil`?

**Comment by srdanrasic** [comment]
It's not a big deal, but I'd like to propagate error further up.

**Comment by matthewcheok** [comment]
Nothing is stopping you from declaring such an initialiser, though you would still have to include the optional version because its part of the protocol:

```
extension Company: JSONDecodable {
    init(object: JSONObject) throws {
        let decoder = JSONDecoder(object: object)
        name = try decoder.decode("name")
        address = try decoder.decode("address")
    }
}
```
