### ISSUE TITLE
JSONEncodable: Enum conversion doesn't work with toJSON() default implementation

### ISSUE THREAD

**Issue by vytis** [matthewcheok/JSONCodable#18]
I have a `String` enum in my struct, but encoding to JSON is failing with `JSONEncodableError.ChildIncompatibleTypeError`. 

It is possible to reproduce the same issue in the current test suite by commenting out `toJSON()` implementation in the `Fruit` struct.

The problem lies in the default implementation of `JSONEncoder.create` in the `switch (value)`  because an enum does not conform to JSONEncodable. 

Tried to fix it in several ways, but unfortunately all failed at the same spot - `extension of protocol 'RawRepresentable' cannot have an inheritance clause`...

**Comment by matthewcheok** [comment]
Unfortunately, this seems to be a limitation of the language right now. For enums, you would have to provide the `toJSON()` method because we can't use `RawRepresentable` as a parameter type (as it has `Self` requirements.)

**Comment by slcheg** [comment]
I faced same problem. It is possible to resolve it if you control or know beforehand all the enums you are going to serialize.
If so, create custom protocol with property returning enum value, called for example anyValue, or convertableValue. Then write extension property with the same name to RawRepresentable, which will return rawValue. Then implement this protocol by all enums you are going to serialize (only inhert, it is not needed to implement method, it is already there by pattern matching!). And last step - add check to this protocol to the toJSON method extension.

Perhaps it worth adding this into library, we cannot wait for Swift team.
