### ISSUE TITLE
Decode JSONString to Structure does not work.

### ISSUE THREAD

**Issue by Christian1313** [matthewcheok/JSONCodable#2]
The protocol extension for `JSONDecodable` with the failable initializer `init?(JSONString: String)` produce the following error message:
`... Cannot find an initializer for type 'UserState' that accepts an argument list of type '(JSONString: String)' ...`

To reproduce this I added the following code at the end of the Playground

```
do {
    let jsonString = try user.JSONString()
    if let user_the_same = User(JSONString: jsonString) {
        print("Same User: \n\(user_the_same)")
    }
} catch {
     print("Error: \(error)")
}
```

To fix this I could add the complete failable initializer `init?(JSONString: String)` to the `User` structure declaration, but this is not how it should work. 

Do you have any Idea?

**Comment by matthewcheok** [comment]
You're right - it looks like it should work but it doesn't.
It could possibly be a language bug in the beta releases.

**Comment by Christian1313** [comment]
I will keep an eye on this. If i have time i try to construct a simple example and file a bug Report with apple.

**Comment by Nadohs** [comment]
I think this is a swift 2 bug, but seems to work as `User.init`

`
if let user_the_same = User.init(JSONString: jsonString) { ....
`

**Comment by Christian1313** [comment]
Thanks @Nadohs.

Very strange bug. Yesterday i create a Playground with the following code and there was the same error. Today that playground works after restarting Xcode and you can see the workaround by Nadohs was not needed.

```
/// A custom protocol
protocol CustomProtocol {
    init()                      // default  initalizer
    init(echoString: String)    // expected initalizer #1
    init?(echoCount: Int)       // expected initalizer #2
}

/// A data structure  with conformance to `CustomProtocol`
struct User: CustomStringConvertible, CustomProtocol  {

    var name = ""
    var description: String {
        get { return "My name is " + name }
    }
}

/// Protocol Extension with default implementations of the initializers #1 #2
extension CustomProtocol {

    init(echoString: String) {
        self.init()
        print("EchoString: \(echoString)")
    }

    init?(echoCount: Int) {
        self.init()
        if echoCount < 0 {
            return nil
        }
        print("EchoCount: \(echoCount)")
    }
}

// Expect user with no name: "My name is"
var u1 = User()
// Expect user with name: "My name is Christian"
var u2 = User(name: "Christian")
// Expect user with no name: "My name is"
var u3 = User(echoString: "Hans")


// Expect user with no name: "My name is"
if let u4 = User(echoCount: 13) {
    print(u4)
} else {
    print("Not Okay. Init should not fail")
}

// Expect user with no name: "My name is"
if let u5 = User(echoCount: -13) {
    print(u5)
} else {
    print("Okay. Init should failed")
}


```

**Comment by matthewcheok** [comment]
Looks like this is fixed in Xcode 7 beta 3?

**Comment by Christian1313** [comment]
Yes Playground works now.
