### ISSUE TITLE
Bool conversion

### ISSUE THREAD

**Issue by olbrichj** [matthewcheok/JSONCodable#23]
It seems like a simple bool conversion is not possible, or am I doing something wrong?

```
struct Book {
    var like: Bool?
}

extension Book: JSONDecodable {
    init(object: JSONObject) throws {
        let decoder = JSONDecoder(object: object)
        like = try decoder.decode("like")
    }
}
```

where JSON is simply:
`{"like": "false"}`

With strings it returns me an optional with a string, with bool it returns nil

**Comment by matthewcheok** [comment]
It should be false without quotes because that is interpreted as a string.

**Comment by olbrichj** [comment]
Thanks :) so the API I'm consuming is broken..
