### ISSUE TITLE
Enums with associated values can't be made decodable.

### ISSUE THREAD

**Issue by seanparsons** [matthewcheok/JSONCodable#29]
If I had a enum (liberally stolen from the Apple docs) like this:

``` swift
enum Barcode {
    case UPCA(Int, Int, Int, Int)
    case QRCode(String)
}
```

Then it can't be made to inherit from JSONDecodable according to the compiler, although it actually gives you a slightly weird error about failable init methods.

**Comment by matthewcheok** [comment]
That's true. Only enums with raw values can be automatically encoded/decoded because JSONDecodable uses the `RawRepresentable` protocol. For this case, I'd suggest using a `JSONTransformer` because there's no obvious way to encode this.

**Comment by seanparsons** [comment]
Closing to cleanup my own list of issues.
