### ISSUE TITLE
Swift 2.2 compilation problem.

### ISSUE THREAD

**Issue by tomergafner** [matthewcheok/JSONCodable#33]
Line 57 in the file JSONDecodable will not compile anymore since it is not valid to have a non-failable initializer requirement be satisfied by a failable one.

https://developer.apple.com/library/mac/documentation/Swift/Conceptual/Swift_Programming_Language/Initialization.html#//apple_ref/doc/uid/TP40014097-CH18-ID224

Great library by the way !

**Comment by matthewcheok** [comment]
Thanks for bringing this up. I'll see if I can get around to this soon!

**Comment by 100mango** [comment]
Same issue. I make the initializer as a non-failable initialize, and it can compile. But should it be non-failable remain as a question.

**Comment by matthewcheok** [comment]
Do you have sample code? I can't reproduce this issue

**Comment by 100mango** [comment]
<img width="1280" alt="2016-04-01 4 53 33" src="https://cloud.githubusercontent.com/assets/5073511/14202399/4cb38296-f82a-11e5-96be-ba4908033989.png">

The original code is form the playground. The screen shot shows what I simply changed.
