### ISSUE TITLE
Problems when the classes to extend with JSONDecodable have a defined initializer. 

### ISSUE THREAD

**Issue by ratranqu** [matthewcheok/JSONCodable#34]
In XCode 7.3 (swift 2.2), adding an initializer to the example class in the playground class to "Decode" breaks JSONDecodable. The same error happens when using the latest DEVELOPMENT-SNAPSHOT-2016-03-01-a version through command line from GitHub. 

``` swift
class Company {
    let name: String
    var address: String?

    init(n: String, a: String?) {
        name = n
        address = a
    }
}
```

``` swift
extension Company: JSONDecodable {
     init(object : JSONObject) throws {
        let decoder = JSONDecoder(object: object)

        name = try decoder.decode("name")
        address = try decoder.decode("address")

    }
}
```

with two (incompatible) errors at the init(object:) in the extension:
**A.** Designated initializer cannot be declared in an extension of 'Company'; did you mean this to be a convenience initializer?
 As such:

``` swift
extension Company: JSONDecodable {
     convenience init(object : JSONObject) throws {
        let decoder = JSONDecoder(object: object)

        name = try decoder.decode("name")
        address = try decoder.decode("address")

    }
}
```

**B.** Initializer requirement 'init(object:)' can only be satisfied by a `required` initializer in the definition of non-final class 'Company'

**Comment by matthewcheok** [comment]
It works on a Struct - I'll investigate Classes as soon as I get the time

**Comment by Nadohs** [comment]
With the new restrictions in swift 2.2 for initializers in extensions, the way to get around this for classes right now seems to be to just move `init(object : JSONObject)` to your class definition.
