### ISSUE TITLE
Decode array of array fail

### ISSUE THREAD

**Issue by 100mango** [matthewcheok/JSONCodable#38]
For example:

``` swift
struct model {
    let areas: [[Float]]
  }

 extension model: JSONDecodable {
    init(object: JSONObject) {
        do {
            let decoder = JSONDecoder(object: object)
            areas = try decoder.decode("areas")
            // Compiler error:  Ambiguous reference to member 'decode'
        }catch{
            fatalError("\(error)")
        }
    }

}
```

**Comment by Nadohs** [comment]
ok, thanks for reporting this. I will look into it later today and get back to you.

**Comment by Nadohs** [comment]
I looked into this issue and believe i have a work around for it, which you can look at in this PR.
https://github.com/matthewcheok/JSONCodable/pull/40

Although it is limited in handling only double nested case where the inner most element is `JSONCompatible` or `JSONDecodable`, but if you needed a triple nested array you would still have an issue.

**Comment by 100mango** [comment]
Thanks. Hope there will be a generic solution.
