### ISSUE TITLE
ambiguous decoder for type UInt64

### ISSUE THREAD

**Issue by vitorhugomagalhaes** [matthewcheok/JSONCodable#39]
Hi,

First of all, thanks for sharing this amazing library.

I'm using some structs with UInt64 and that caused a compilation error indicating references to ambiguous decode functions.

My workaround was to extend JSONDecoder but this does not work too. Compilation works fine but it throws error while decoding.

```
private struct StorePromotionItem {
    let banner: String
    let icon: String
    var saleOptionId: UInt64?
    var productOfferId: UInt64?
}

extension StorePromotionItem: JSONDecodable {
    init(object: JSONObject) throws {
        let decoder = JSONDecoder(object: object)
        banner = try decoder.decode("banner")
        icon = try decoder.decode("icon")
        saleOptionId = try decoder.decode("sale_option_id")
        productOfferId = try decoder.decode("product_offer_id")
    }
}
```

```
extension JSONDecoder {
    public func decode(key: String) throws -> UInt64 {
        let JSONTransformerStringToUInt64 = JSONTransformer<String, UInt64>(
            decoding: {
                UInt64($0)
            },
            encoding: {
                String($0)
        })

        return try decode(key, transformer: JSONTransformerStringToUInt64)
    }
}
```

Thanks,

**Comment by Nadohs** [comment]
Hi there, for UInt64 you can use a transformer and you should not need to extend JSONDecoder with another decoding case.

```
extension StorePromotionItem: JSONDecodable {
    init(object: JSONObject) throws {
        let decoder = JSONDecoder(object: object)
        banner = try decoder.decode("banner")
        icon = try decoder.decode("icon")
        saleOptionId = try decoder.decode("sale_option_id", transformer: intToInt64)
        productOfferId = try decoder.decode("product_offer_id", transformer: intToInt64)
    }
}

let intToInt64 = JSONTransformer<Int, UInt64>(
    decoding: { UInt64($0) },
    encoding: { Int($0) })
```

Using a transform in this way worked fine in my tests, converting the value properly.

**Comment by Nadohs** [comment]
Although,... I can image this solution may have some precision loss (runtime crash) going from Int -> UInt64... if you are expecting values from the JSON that could be larger than a signed 64-bit integer value.  If that is your issue then unfortunately I do not have a good answer for you right now...

**Comment by vitorhugomagalhaes** [comment]
That's true I cannot cast from Int -> UInt64.

Extending the decoder is not an option ?

**Comment by Nadohs** [comment]
Actually building a transformer from NSNumber -> UInt64 seems to work alright, in my tests it can handle a UInt64.max value.

```
let toUInt64 = JSONTransformer<NSNumber, UInt64>(
    decoding: { UInt64($0.unsignedLongLongValue)},
    encoding: {NSNumber(unsignedLongLong:$0)})
```

**Comment by Nadohs** [comment]
Let me know if you have any trouble with the `NSNumber -> UInt64` transformer solution, otherwise for now I am closing this issue. Thanks!
