### ISSUE TITLE
Not able to read using jsondecodable

### ISSUE THREAD

**Issue by aleemilu75** [matthewcheok/JSONCodable#41]
[
  {
    "ID": 568,
    "av": 125435865,
    "ad": "2016-06-07",
    "ar": 0,
    "at": 0,
    "ah": 0,
    "aj": "te"
  }
]

struct Messages {
    let id: [[String:AnyObject]]?
}

**Comment by matthewcheok** [comment]
Your JSON is an array of a single dictionary. You can only do this if you use `Messages` to process one level higher.

**Comment by Nadohs** [comment]
I have an implementation working for this. Only on swift-3 branch right now though. PR here: https://github.com/matthewcheok/JSONCodable/pull/42/
