### ISSUE TITLE
new release please? :)

### ISSUE THREAD

**Issue by ratranqu** [matthewcheok/JSONCodable#43]
Hi there,

could we have a new release with the latest fixes/additions please? :)

thx!

**Comment by mxcl** [comment]
So, this project is abandoned then…?

**Comment by matthewcheok** [comment]
There are Swift 3 related changes on the develop branch - but we're waiting for the final release before merging into master.

**Comment by syshen** [comment]
Swift3 and Xocde8 are already released, any plan of when to merge the swift3 support into master branch?

**Comment by mxcl** [comment]
I switched to a maintained project already.

**Comment by ratranqu** [comment]
Matthew, this branch: https://gitlab.com/katalysis/JSONCodable should be ready for swift 3.0, spm and linux. I will do a PR when I have more time.

**Comment by ratranqu** [comment]
$ cat Package.swift 
import PackageDescription

let package = Package(
    name: "JSONCodableTest",
dependencies: [
    .Package(url: "git@gitlab.com:katalysis/JSONCodable.git", majorVersion: 3, minor: 1),
    ]
)

**Comment by Nadohs** [comment]
Hi there, we are indeed working on making a release this week, should be either today or tomorrow
see this comment: https://github.com/matthewcheok/JSONCodable/pull/53#issuecomment-248156909
for this branch: https://github.com/matthewcheok/JSONCodable/tree/develop2

**Comment by ratranqu** [comment]
Thanks much! if you can keep Linux support and add Package manager support, that would be awesome!
