### ISSUE TITLE
Empty array instead of MissingTypeError

### ISSUE THREAD

**Issue by lightsprint09** [matthewcheok/JSONCodable#50]
In [JSONDecodable Line 197](https://github.com/matthewcheok/JSONCodable/blob/master/JSONCodable/JSONDecodable.swift#L197) an empty array gets return. Why is there no MissingTypeError thrown. This pattern can be found in more places.

It does not make sense to return an empty array if the key is unavailable.

**Comment by Nadohs** [comment]
thanks for fixing this 👍
