### ISSUE TITLE
Use proper SemVer in release version tags

### ISSUE THREAD

**Issue by mokagio** [matthewcheok/JSONCodable#55]
The tag of each version should use proper [Semantic Versioning](http://semver.org/), or it won't work with tools like Carthage, which expect valid version tags.

For example: the [latest version](https://github.com/matthewcheok/JSONCodable/releases/tag/3.0) is tagged `3.0`. This is not valid SemVer. It should be `3.0.0`.

Not sure if it's worth rewriting the current tags, but it's definitely something to keep in mind for the future.

Thanks

**Comment by mokagio** [comment]
> or it won't work with tools like Carthage, which expect valid version tags.

I apologize. It wasn't working due to another issue with my setup, not with how the tag was defined in this repo.

Nevertheless Imho using full SemVer would be more accurate.

**Comment by Nadohs** [comment]
thanks, glad you were able to get it to work. I will keep that in mind for version going forward.
