### ISSUE TITLE
Cocoapods repo update?

### ISSUE THREAD

**Issue by xmkevinchen** [matthewcheok/JSONCodable#58]
Hi Cocoapods repo version is still 2.1, would you like to update the version to Cocoapods?

[Cocoapods JSONCodable](https://cocoapods.org/pods/JSONCodable)

**Comment by proauto** [comment]
[!] Unable to satisfy the following requirements:
- `JSONCodable (~> 3.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `JSONCodable (~> 3.0)`.

You have either:
- out-of-date source repos which you can update with `pod repo update`.
- mistyped the name or version.
- not added the source repo that hosts the Podspec to your Podfile.

I also think version is not updated

**Comment by Nadohs** [comment]
ok I attempted to update the podspec on release, but clearly its not working, will look into this today

**Comment by Nadohs** [comment]
Cocoapods should be working now. Updated trunk repo, tested, and working for me.
