### ISSUE TITLE
Push to CocoaPods

### ISSUE THREAD

**Issue by kleiram** [matthewcheok/JSONCodable#6]
It'd be great if this library would be available through CocoaPods! I see there's a `podspec` file already, so it would be simple, right?

**Note:** For now, anyone who wants to use it you can use the following in your `Podfile`:

``` ruby
pod 'JSONCodable', :git => 'https://github.com/matthewcheok/JSONCodable.git'
```

**Comment by matthewcheok** [comment]
Last I tried something was breaking with the Xcode betas. Will try again tonight

**Comment by matthewcheok** [comment]
Pushed! Let me know if it works (or not)
