### ISSUE TITLE
Decoding values within child keys?

### ISSUE THREAD

**Issue by tonyarnold** [matthewcheok/JSONCodable#7]
Given the following data structure, how would I extract values nested inside multiple keys? 

``` json
{
    "links": {
         "some_link": "http://blah.com/",
         "other_link": "http://derp.com/"
    }
}
```

With other frameworks like Argo, I can pull out values from child keys using syntax like `["links", "some_link"]`. I couldn't find anything similar on the `decode()` method.

**Comment by matthewcheok** [comment]
You can do this in v1.1 by using keys like `links.some_link` and `links.other_link`.

**Comment by tonyarnold** [comment]
Excellent, thanks @matthewcheok!
